spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    password: hr
  jpa:    show-sql: true
server:  port: 7070
  
management:  endpoints:    web:      exposure:        include:        - "*"
  endpoint:
    shutdown:
      enabled: true   info:    build:
      artifcatId: '@project.artifcat@'
      groupId: 'project.groupId@'
    java:
      version: 8.0